apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
      app: phpmyadmin
spec:
  ports:
    - name: phpmyadmin
      port: 5000
  selector:
    app: phpmyadmin
  type: LoadBalancer
  # LoadBalancerIP:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: mzomeno-phpmyadmin
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
