apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    app: ftps
  ports:
  - name: ftps
    protocol: TCP
    port: 21
    nodePort: 21
  - name: ftps-pasv
    protocol: TCP
    port: 32121
    nodePort: 32121
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: mzomeno-ftps
        ports:
        - containerPort: 21
        - containerPort: 32121
        imagePullPolicy: Never
