apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
      - name: wordpress
        protocol: TCP
        port: 5050
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
---
# OPTIONAL
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-storage
  labels:
    app: wordpress
spec:
  storageClassName: wordpress
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-storage
      containers:
      - name: wordpress
        image: mzomeno-wordpress
        ports:
        - containerPort: 5050
          volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
