apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: 42Madrid
      protocol: layer2
      addresses:
      - 192.168.99.0-192.168.99.255 # Pool for the 42Madrid local network
